; MIT No Attribution
;
; Permission is hereby granted, free of charge, to any person obtaining a copy of this
; software and associated documentation files (the "Software"), to deal in the Software
; without restriction, including without limitation the rights to use, copy, modify,
; merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
; permit persons to whom the Software is furnished to do so.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
; INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
; PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
; HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
; OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
; SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

; Adds Alt+<key> and Alt+Shift+<key> hotkeys for many unicode characters.

!a:: Send 'α'
!+a:: Send '∧'
!b:: Send 'β'
!+b:: Send 'ß'
!c:: Send '©'
!+c:: Send '¢'
!d:: Send 'δ'
!+d:: Send 'Δ'
!e:: Send '∈'
!+e:: Send '∉'
!f:: Send 'φ'
!+f:: Send 'Φ'
!g:: Send 'γ'
!+g:: Send 'Γ'
!h:: Send '❤'
!+h:: Send '½'
!i:: Send '∞'
!+i:: Send '∫'
!j:: Send '¡'
!+j:: Send '¿'
!k:: Send '⌫'
!+k:: Send '⌘'
!l:: Send 'ℓ'
!+l:: Send 'λ'
!m:: Send 'μ'
!+m:: Send '✓'
!n:: Send '∩'
!+n:: Send 'ℕ'
!o:: Send '°'
!+o:: Send 'Ω'
!p:: Send 'π'
!+p:: Send 'Π'
!q:: Send '♪'
!+q:: Send 'ℚ'
!r:: Send '®'
!+r:: Send 'ρ'
!s:: Send 'σ'
!+s:: Send 'Σ'
!t:: Send 'θ'
!+t:: Send '†'
!u:: Send '∪'
!+u:: Send '↑'
!v:: Send '↓'
!+v:: Send '∨'
!w:: Send 'ω'
!+w:: Send '₩'
!x:: Send '×'
!+x:: Send '⊕'
!y:: Send '¥'
!+y:: Send 'ý'
!z:: Send 'ζ'
!+z:: Send 'ℤ'

!1:: Send '₁'
!2:: Send '₂'
!3:: Send '₃'
!4:: Send '₄'
!5:: Send '₅'
!6:: Send '₆'
!7:: Send '₇'
!8:: Send '₈'
!9:: Send '₉'
!0:: Send '₀'
!+1:: Send '¹'
!+2:: Send '²'
!+3:: Send '³'
!+4:: Send '⁴'
!+5:: Send '⁵'
!+6:: Send '⁶'
!+7:: Send '⁷'
!+8:: Send '⁸'
!+9:: Send '⁹'
!+0:: Send '⁰'


!`:: Send '≈'
!+`:: Send '≅'
!-:: Send '—'
!+-:: Send '¬'
!=:: Send '≠'
!+=:: Send '±'
![:: Send '⊂'
!+[:: Send '≤'
!]:: Send '⊃'
!+]:: Send '≥'
!\:: Send '▲'
!+\:: Send '▼'
!;:: Send '∝'
!+;:: Send '≡'
!':: Send '√'
!+':: Send '∛'
!,:: Send '…'
!+,:: Send '←'
!.:: Send '•'
!+.:: Send '→'
!/:: Send '÷'
!+/:: Send '‽'
!Space:: Send ' ' ;Non-breaking space
!+Space:: Send '█'
